### CHANGE BEFORE DEPLOY ####
#baseurl = "http://10.0.0.10/"
baseurl = "https://www.degoll.net/"
languageCode = "en-us"
title = "Michael DeGoll"
theme = "PaperMod"
disqusShortname = "mdegoll"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = "G-DX23EZT920"
# Define how many posts should appear on a site
[pagination]
	pagerSize = 10

[services]
	[services.googleAnalytics]
		id = "G-DX23EZT920"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[params]
	# PaperMod theme settings
	env = "production"
	author = "Michael DeGoll"
	defaultTheme = "light"
	disableThemeToggle = true

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Michael DeGoll"
	description = "CTO & Agent Orchstrator"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "Me2.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Salesforce"
		bio2 = "Full Stack Architect"
		# The icons will be shown if you enter your username
		twitter = ""
		github = "mdegoll"
		dribbble = ""
		facebook = ""
		googleplus = ""
		flickr = ""
		linkedin = "https://www.linkedin.com/in/michael-j-degoll/"

		copyright = [
			"&copy; Michael DeGoll",
			"Design: [Michael DeGoll](//degoll.net)",
			"Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "Your Trusted Advisor for Salesforce"
		content = "<br>[Send me an email](https://www.degoll.net/#contact-form) to start the conversation."


	[params.portfolio]
		hide  = false
		title = "Most Recent Tools"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "https://salesforce.com/"
			thumb = "thumbs/salesforce.png"
			title = "Salesforce"
			description = "Full Stack Architect"

		[[params.portfolio.gallery]]
			image = "https://www.mulesoft.com/"
			thumb = "thumbs/mulesoft.png"
			title = "Mulesoft"
			description = "Mulesoft Certified"

		[[params.portfolio.gallery]]
			image = "https://www.jitterbit.com"
			thumb = "thumbs/jitterbit.jpg"
			title = "Jittbit Integration."
			description = "Salesforce Integration"

		[[params.portfolio.gallery]]
			image = "https://www.ibm.com/software/products/en/ibm-integration-bus"
			thumb = "thumbs/IIB.jpg"
			title = "IBM Integration Bus"
			description = "Message Broker v9 Certified"

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Feel free to send me an email about your business issues or just to say hello!"

		address = [
			"Currently:",
			"Seattle, WA",
		]
		phone = "+1-610-462-4393"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "michael@mdegoll.net"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"

	[params.profileMode]
		enabled = true
		title = "Michael DeGoll"
		subtitle = "Full Stack Salesforce Architect"
		imageUrl = "images/Me2.png"
		imageTitle = "Michael DeGoll"
		imageWidth = 160
		imageHeight = 160

	[[params.profileMode.buttons]]
		name = "Blog"
		url = "/post/"

	[[params.profileMode.buttons]]
		name = "Email"
		url = "mailto:michael@degoll.net"

	[[params.socialIcons]]
		name = "github"
		url = "https://github.com/mdegoll"

	[[params.socialIcons]]
		name = "linkedin"
		url = "https://www.linkedin.com/in/michael-j-degoll"

	[[params.socialIcons]]
		name = "email"
		url = "mailto:michael@degoll.net"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "About"
	url  = "/about/"
	weight = 5

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
